export {
  listarSolicitudes,
  obtenerSolicitud,
  crearSolicitud,
  actualizarSolicitud,
  eliminarSolicitud,
  descargarExcelSolicitud,
  descargarPdfSolicitud,
  descargarTodasLasSolicitudes,
  enviarCorreoPrueba,
  enviarSolicitudPorCorreo,
  destinatariosDeSolicitud,
  resultadosDeShipTo,
} from './lib/api'
export {
  listarCamposConfig,
  guardarCamposConfig,
  listarTiposAplicacion,
  crearTipoAplicacion,
  actualizarTipoAplicacion,
  eliminarTipoAplicacion,
  listarLineasProceso,
  crearLineaProceso,
  actualizarLineaProceso,
  eliminarLineaProceso,
  listarAnalitosConfig,
  crearAnalitoConfig,
  actualizarAnalitoConfig,
  eliminarAnalitoConfig,
  listarCamposTipoAplicacion,
  crearCampoTipoAplicacion,
  actualizarCampoTipoAplicacion,
  eliminarCampoTipoAplicacion,
  listarLaboratoriosConfig,
  crearLaboratorioConfig,
  actualizarLaboratorioConfig,
  eliminarLaboratorioConfig,
  listarCategoriasAnaliticas,
  crearCategoriaAnalitica,
  actualizarCategoriaAnalitica,
  eliminarCategoriaAnalitica,
  listarProductosConfig,
  crearProductoConfig,
  actualizarProductoConfig,
  eliminarProductoConfig,
} from './lib/api'
export type {
  Solicitud,
  SolicitudInput,
  Laboratorio,
  CampoConfig,
  OpcionConfig,
  OpcionInput,
  AnalitoConfig,
  AnalitoInput,
  CampoTipoAplicacionConfig,
  CampoTipoAplicacionInput,
  LaboratorioConfig,
  LaboratorioInput,
  CategoriaAnaliticaConfig,
  CategoriaAnaliticaInput,
  ProductoConfig,
  ProductoInput,
  ContactoResultado,
} from './lib/tipos'
export { LABORATORIOS } from './lib/tipos'
