export { useDashboardSummary } from './hooks/useDashboardSummary'
export { useAreaDashboardSummary } from './hooks/useAreaDashboardSummary'
export { ModuloCard } from './components/ModuloCard'
export { AreaHero } from './components/AreaHero'
export type { ResumenDashboard, CargaReciente, AlertaProceso, ResumenArea, ReporteEnviado } from './types'
