export {
  listarTablas,
  verTabla,
  auditar,
  estadoStaging,
  crearStaging,
  descartarStaging,
  corregirGrupo,
  corregirValores,
  historialStaging,
  deshacer,
  valoresColumna,
  promover,
  urlExportar,
} from './lib/api'
export type {
  InfoTabla,
  PaginaTabla,
  GrupoInconsistencia,
  ResultadoAuditoria,
  EstadoStaging,
  CorregirGrupoInput,
  CorregirValoresInput,
  ResultadoCorreccion,
  EntradaHistorial,
  ResultadoDeshacer,
  ValorColumna,
  ValoresColumna,
} from './lib/tipos'
