export interface MapaSQLEntry {
  col: string
  tabla: string
  campo: string
  tipo: 'sol' | 'prod' | 'res' | 'skip' | 'warn'
  nota: string
}

// Relación columna Excel → tabla.campo SQL, tal como la definió el laboratorio.
export const SQL_MAP: MapaSQLEntry[] = [
  { col: 'Informe', tabla: 'solicitud', campo: 'nro_solicitud', tipo: 'sol', nota: '' },
  { col: 'Cliente', tabla: 'solicitud / cliente', campo: 'sold_to_raw → cliente.nombre', tipo: 'sol', nota: 'strip()' },
  { col: 'Sucursal', tabla: 'solicitud / planta', campo: 'ship_to_raw → planta.nombre', tipo: 'sol', nota: 'strip + upper + mapa' },
  { col: 'Fecha de muestreo', tabla: 'solicitud', campo: 'fecha_muestreo', tipo: 'sol', nota: 'parser multi-formato' },
  { col: 'Fecha entrada', tabla: 'solicitud', campo: 'fecha_entrada', tipo: 'sol', nota: 'parser multi-formato' },
  { col: 'Fecha análisis', tabla: 'solicitud', campo: 'fecha_analisis', tipo: 'sol', nota: 'parser multi-formato' },
  { col: 'Variedad', tabla: 'solicitud', campo: 'variedad', tipo: 'sol', nota: '' },
  { col: 'Cámara', tabla: 'solicitud', campo: 'nro_camara', tipo: 'sol', nota: 'Usar esta, ignorar col N°Cámara' },
  { col: 'TIPO APP', tabla: 'producto_aplicado', campo: 'tipo_aplicacion', tipo: 'prod', nota: 'strip + mapa canónico' },
  { col: 'Posición', tabla: 'solicitud', campo: 'posicion_muestreo', tipo: 'sol', nota: 'Usar esta, ignorar col Posición Muestreo' },
  { col: 'Observaciones', tabla: 'solicitud', campo: 'observacion', tipo: 'sol', nota: '' },
  { col: 'Dosis', tabla: 'solicitud', campo: 'observacion_2', tipo: 'sol', nota: 'Texto libre, sin modificar' },
  { col: 'APP', tabla: 'producto_aplicado', campo: 'producto_raw', tipo: 'prod', nota: '' },
  { col: 'Cód. Productor (CSG)', tabla: 'solicitud', campo: 'csg', tipo: 'sol', nota: '' },
  { col: 'Cámara Húmeda', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: 'No existe en schema' },
  { col: 'Línea', tabla: 'solicitud', campo: 'nro_linea', tipo: 'sol', nota: '' },
  { col: 'Kg \nprocesados', tabla: 'solicitud', campo: 'kg_procesados', tipo: 'sol', nota: '' },
  { col: 'N° Cámara', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: 'Duplica col Cámara' },
  { col: 'Lote', tabla: 'solicitud', campo: 'lote', tipo: 'sol', nota: '' },
  { col: 'Posición Muestreo', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: 'Duplica col Posición' },
  { col: 'FDL_dosis', tabla: 'producto_aplicado', campo: 'dosis (FDL)', tipo: 'prod', nota: 'Texto libre, sin modificar' },
  { col: 'IMZ_dosis', tabla: 'producto_aplicado', campo: 'dosis (IMZ)', tipo: 'prod', nota: 'Texto libre, sin modificar' },
  { col: 'PYR_dosis', tabla: 'producto_aplicado', campo: 'dosis (PYR)', tipo: 'prod', nota: 'Texto libre, sin modificar' },
  { col: 'TBZ_dosis', tabla: 'producto_aplicado', campo: 'dosis (TBZ)', tipo: 'prod', nota: 'Texto libre, sin modificar' },
  { col: 'AZOX_dosis', tabla: 'producto_aplicado', campo: 'dosis (AZOX)', tipo: 'prod', nota: 'Texto libre, sin modificar' },
  { col: 'FNHE_dosis', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: 'Analito no en catálogo, columna vacía' },
  { col: 'TEBU_dosis', tabla: 'producto_aplicado', campo: 'dosis (TEBU)', tipo: 'prod', nota: 'Texto libre, sin modificar' },
  { col: 'Observación adicional', tabla: 'solicitud', campo: 'observacion_2', tipo: 'sol', nota: '' },
  { col: 'Tratamiento', tabla: 'producto_aplicado', campo: 'linea_proceso', tipo: 'prod', nota: '' },
  { col: 'Línea de \nProceso', tabla: 'producto_aplicado', campo: 'linea_proceso', tipo: 'prod', nota: '' },
  { col: 'Fecha \nSolicitud', tabla: 'solicitud', campo: 'fecha_solicitud', tipo: 'sol', nota: 'parser multi-formato' },
  { col: 'Codigo interno\ndel cliente', tabla: 'solicitud', campo: 'nro_orden', tipo: 'sol', nota: '' },
  { col: 'Nombre del responsable', tabla: 'solicitud', campo: 'nombre_muestreador', tipo: 'sol', nota: '' },
  { col: 'Asesor \nde servicio', tabla: 'solicitud', campo: 'solicitante', tipo: 'sol', nota: '' },
  { col: 'Reference/s', tabla: 'solicitud', campo: 'referencia', tipo: 'sol', nota: '' },
  { col: 'Referencia reporte proceso+O:T', tabla: 'solicitud', campo: 'referencia_proceso', tipo: 'sol', nota: '' },
  { col: 'orden', tabla: 'solicitud', campo: 'nro_orden', tipo: 'sol', nota: 'Verificar vs col 31' },
  { col: 'CROP', tabla: 'solicitud', campo: 'especie', tipo: 'sol', nota: 'strip + title()' },
  { col: 'FDL FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (FDL)', tipo: 'res', nota: 'ND→texto, str numérico→float, resto→NULL' },
  { col: 'IMZ FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (IMZ)', tipo: 'res', nota: 'ND→texto, resto→NULL' },
  { col: 'PYR FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (PYR)', tipo: 'res', nota: 'ND→texto, resto→NULL' },
  { col: 'TBZ FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (TBZ)', tipo: 'res', nota: 'ND→texto, resto→NULL' },
  { col: 'AZOXFINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (AZOX)', tipo: 'res', nota: 'ND→texto, resto→NULL' },
  { col: 'TEBU FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (TEBU)', tipo: 'res', nota: 'ND→texto, <L.C→NULL' },
  { col: 'DFN FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (DFN)', tipo: 'warn', nota: 'DFN no en catálogo → analito_raw' },
  { col: 'DPA FINAL', tabla: 'resultado', campo: 'valor_num/valor_texto (DPA)', tipo: 'res', nota: 'ND→texto, resto→NULL' },
  { col: 'Nombre reporte', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: 'Campo presentación' },
  { col: 'Tipo de servicio', tabla: 'solicitud', campo: 'tipo_servicio', tipo: 'sol', nota: 'Normalizar capitalización' },
  { col: 'Columna3', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: '9 valores, contenido irrelevante' },
  { col: 'FDL QUITECA ', tabla: '—', campo: '(ignorar por ahora)', tipo: 'skip', nota: 'Agregar analito a catálogo si se requiere' },
  { col: 'QUITECA PYR', tabla: '—', campo: '(ignorar por ahora)', tipo: 'skip', nota: '' },
  { col: 'QUITECA TEBU', tabla: '—', campo: '(ignorar por ahora)', tipo: 'skip', nota: '0 valores' },
  { col: 'DPA QUITECA', tabla: '—', campo: '(ignorar por ahora)', tipo: 'skip', nota: '' },
  { col: 'Informe Quiteca', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: '' },
  { col: 'Temporada ', tabla: 'solicitud', campo: 'temporada', tipo: 'sol', nota: '' },
  { col: 'Semana entrada', tabla: 'solicitud', campo: 'semana_entrada', tipo: 'sol', nota: '' },
  { col: 'Informe QUITECA2', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: '' },
  { col: 'Informe AGF', tabla: '—', campo: '(ignorar)', tipo: 'skip', nota: '' },
  { col: 'Laboratorio', tabla: 'solicitud', campo: 'laboratorio', tipo: 'sol', nota: '' },
  { col: 'SEMANA', tabla: 'solicitud', campo: 'semana_muestreo', tipo: 'sol', nota: '' },
  { col: 'MES', tabla: 'solicitud', campo: 'mes', tipo: 'sol', nota: '' },
]
