export { SQL_MAP } from './lib/sqlMap'
export type { MapaSQLEntry } from './lib/sqlMap'
export { homogenize } from './lib/homogenizar'
export type { FilaIngest, CambioHomogenizacion } from './lib/homogenizar'
export { auditarParaCarga, CAMPO_REQUERIDO } from './lib/auditoria'
export type { Auditoria, Duplicado, AlertaCampo } from './lib/auditoria'
export { leerExcel, descargarExcel } from './lib/leerExcel'
export { previsualizarCarga, confirmarCarga, listarPendientes, aprobarPendiente, descartarPendiente } from './lib/api'
export type { ResumenCarga, DetalleFilaCarga, RespuestaCarga, Pendiente, MotivoPendiente } from './lib/api'
